### ISSUE TITLE
Creating an application in projectview dumps files in root of project

### ISSUE THREAD

**Issue by seancorfield** [tpryan/Apptacular#10]
A naîve attempt to use Apptacular would be to open a project, create a folder for the app and then right-click > Apptacular > Create application on that new folder. The result is the application is generated into the root of the project (and doesn't actually work because it has references to .cfc.table[] in types (notice leading .).

If would be nice if Apptacular could detect this and explain that you need to create the application from the RDS view instead.

**Comment by tpryan** [comment]
Grrr. I thought I had fixed that.  It should dump it where they right click.

**Comment by seancorfield** [comment]
OK, that's sort of what I expected so I was a bit surprised it didn't. Let me know if I can help test that more.
