### ISSUE TITLE
svn error

### ISSUE THREAD

**Issue by godsmustbcrazy** [tpryan/Apptacular#24]
If you add the apptacular project to an svn you get an error when trying to regenerate the application ,it throws an error saying "Datasource .svn could not be found" 

Log file here http://64.72.142.162/apptacular/2010-08-13_11-42-54-142.html

**Comment by tpryan** [comment]
Fixed bug where .svn folders screwed up Application generation. 

Closed by 67e3e00de8290d0ae88b953800f06975eaad48f7.
