### ISSUE TITLE
Element IDENTITY.IDENTITY is undefined in a CFML structure referenced as part of an expression.

### ISSUE THREAD

**Issue by willcor** [tpryan/Apptacular#27]
Encountered this error after updating to version 1.000299.  when creating an application using MSSQL 2008 database. But it does work on Apache Derby Database.

**Comment by jasonhutton-zz** [comment]
Getting same error here. Using MSSQL 2008. Here is the log file from the error:

struct

Detail: [empty string]
ErrNumber: 0
Message: Element IDENTITY.IDENTITY is undefined in a CFML structure referenced as part of an expression.
Resolvedname: [empty string]
StackTrace: coldfusion.runtime.UndefinedElementException: Element IDENTITY.IDENTITY is undefined in a CFML structure referenced as part of an expression.
    at coldfusion.runtime.DotResolver.resolveSplitNameInMap(DotResolver.java:109)
    at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1559)
    at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1777)
    at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1769)
    at cftable2ecfc2117812495$funcDETERMINEAUTOINCMSSQL.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:837)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
    at cftable2ecfc2117812495$funcDETERMINEAUTOINC.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:791)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360)
    at cftable2ecfc2117812495$funcPOPULATETABLE.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:783)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
    at cftable2ecfc2117812495$funcINIT.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:88)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
    at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:8609)
    at coldfusion.runtime.CFPage._createObject(CFPage.java:8577)
    at cfdatasource2ecfc1691690504$funcPOPULATETABLES.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\datasource.cfc:92)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582)
    at cfdatasource2ecfc1691690504$funcINIT.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\datasource.cfc:35)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337)
    at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:8609)
    at coldfusion.runtime.CFPage._createObject(CFPage.java:8577)
    at cfhandlerGenerate2ecfm1878019093.runPage(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\handlerGenerate.cfm:133)
    at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:231)
    at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:416)
    at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
    at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:360)
    at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48)
    at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
    at coldfusion.filter.PathFilter.invoke(PathFilter.java:94)
    at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:27)
    at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70)
    at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
    at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
    at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46)
    at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
    at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
    at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
    at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126)
    at coldfusion.CfmServlet.service(CfmServlet.java:200)
    at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
    at jrun.servlet.FilterChain.doFilter(FilterChain.java:86)
    at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
    at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
    at jrun.servlet.FilterChain.doFilter(FilterChain.java:94)
    at jrun.servlet.FilterChain.service(FilterChain.java:101)
    at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106)
    at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42)
    at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286)
    at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543)
    at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203)
    at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320)
    at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428)
    at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266)
    at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66)
TagContext:  
    [array]
    1) [struct]
        COLUMN: 0
        ID: CF_DOTRESOLVER
        LINE: 837
        RAW_TRACE: at cftable2ecfc2117812495$funcDETERMINEAUTOINCMSSQL.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:837)
        TEMPLATE: C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc
        TYPE: CFML 
    2) [struct]
        COLUMN: 0
        ID: CF_UDFMETHOD
        LINE: 791
        RAW_TRACE: at cftable2ecfc2117812495$funcDETERMINEAUTOINC.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:791)
        TEMPLATE: C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc
        TYPE: CFML 
    3) [struct]
        COLUMN: 0
        ID: CF_TEMPLATEPROXY
        LINE: 783
        RAW_TRACE: at cftable2ecfc2117812495$funcPOPULATETABLE.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:783)
        TEMPLATE: C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc
        TYPE: CFML 
    4) [struct]
        COLUMN: 0
        ID: CF_UDFMETHOD
        LINE: 88
        RAW_TRACE: at cftable2ecfc2117812495$funcINIT.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc:88)
        TEMPLATE: C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\table.cfc
        TYPE: CFML 
    5) [struct]
        COLUMN: 0
        ID: CF_CFPAGE
        LINE: 92
        RAW_TRACE: at cfdatasource2ecfc1691690504$funcPOPULATETABLES.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\datasource.cfc:92)
        TEMPLATE: C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\datasource.cfc
        TYPE: CFML 
    6) [struct]
        COLUMN: 0
        ID: CF_UDFMETHOD
        LINE: 35
        RAW_TRACE: at cfdatasource2ecfc1691690504$funcINIT.runFunction(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\datasource.cfc:35)
        TEMPLATE: C:\Inetpub\wwwroot\Adobe Apptacular\handlers\cfc\db\datasource.cfc
        TYPE: CFML 
    7) [struct]
        COLUMN: 0
        ID: CF_CFPAGE
        LINE: 133
        RAW_TRACE: at cfhandlerGenerate2ecfm1878019093.runPage(C:\Inetpub\wwwroot\Adobe Apptacular\handlers\handlerGenerate.cfm:133)
        TEMPLATE: C:\Inetpub\wwwroot\Adobe Apptacular\handlers\handlerGenerate.cfm
        TYPE: CFML 
Type: Expression
element: IDENTITY.IDENTITY
objectType:  
    [object of java.lang.Class]
    Class Name: java.lang.Class
    Methods:  
        asSubclass(java.lang.Class) returns java.lang.Class 
        cast(java.lang.Object) returns java.lang.Object 
        desiredAssertionStatus() returns boolean 
        forName(java.lang.String, boolean, java.lang.ClassLoader) returns java.lang.Class 
        forName(java.lang.String) returns java.lang.Class 
        getAnnotation(java.lang.Class) returns java.lang.annotation.Annotation 
        getAnnotations() returns java.lang.annotation.Annotation[] 
        getCanonicalName() returns java.lang.String 
        getClassLoader() returns java.lang.ClassLoader 
        getClasses() returns java.lang.Class[] 
        getComponentType() returns java.lang.Class 
        getConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
        getConstructors() returns java.lang.reflect.Constructor[] 
        getDeclaredAnnotations() returns java.lang.annotation.Annotation[] 
        getDeclaredClasses() returns java.lang.Class[] 
        getDeclaredConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
        getDeclaredConstructors() returns java.lang.reflect.Constructor[] 
        getDeclaredField(java.lang.String) returns java.lang.reflect.Field 
        getDeclaredFields() returns java.lang.reflect.Field[] 
        getDeclaredMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
        getDeclaredMethods() returns java.lang.reflect.Method[] 
        getDeclaringClass() returns java.lang.Class 
        getEnclosingClass() returns java.lang.Class 
        getEnclosingConstructor() returns java.lang.reflect.Constructor 
        getEnclosingMethod() returns java.lang.reflect.Method 
        getEnumConstants() returns java.lang.Object[] 
        getField(java.lang.String) returns java.lang.reflect.Field 
        getFields() returns java.lang.reflect.Field[] 
        getGenericInterfaces() returns java.lang.reflect.Type[] 
        getGenericSuperclass() returns java.lang.reflect.Type 
        getInterfaces() returns java.lang.Class[] 
        getMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
        getMethods() returns java.lang.reflect.Method[] 
        getModifiers() returns int 
        getName() returns java.lang.String 
        getPackage() returns java.lang.Package 
        getProtectionDomain() returns java.security.ProtectionDomain 
        getResource(java.lang.String) returns java.net.URL 
        getResourceAsStream(java.lang.String) returns java.io.InputStream 
        getSigners() returns java.lang.Object[] 
        getSimpleName() returns java.lang.String 
        getSuperclass() returns java.lang.Class 
        getTypeParameters() returns java.lang.reflect.TypeVariable[] 
        isAnnotation() returns boolean 
        isAnnotationPresent(java.lang.Class) returns boolean 
        isAnonymousClass() returns boolean 
        isArray() returns boolean 
        isAssignableFrom(java.lang.Class) returns boolean 
        isEnum() returns boolean 
        isInstance(java.lang.Object) returns boolean 
        isInterface() returns boolean 
        isLocalClass() returns boolean 
        isMemberClass() returns boolean 
        isPrimitive() returns boolean 
        isSynthetic() returns boolean 
        newInstance() returns java.lang.Object 
        toString() returns java.lang.String

---

Thanks
Jason

**Comment by timbrown** [comment]
Have the same issue..any help would be much appreciated.

**Comment by willcor** [comment]
downloaded the latest version from RIAForge and it's working perfectly! Thank You.

**Comment by tpryan** [comment]
Sorry to not respond sooner.  Can you post a table create sql?  will help me trouble shoot.

**Comment by garence** [comment]
Running into identical issue, can someone shed some light on this front?

**Comment by JohnnyP10** [comment]
I am seeing this with CF9 and Sql2008 and when i tried debugging, it seems to be trying to call sys tables like sys.change_tracking_tables and sys.change_tracking_databases.  I assume it has something to do with sql permissions or it is just SQL 2008.  I had to edit the datasource.cfc with all the table names.  Terry, i will email you the code that i used.

**Comment by garence** [comment]
In hopes it helps, I am willing to email code too - though I'm not sure what to send ... let me know and I'll contribute what I have.

**Comment by htezcan** [comment]
I have the same problem using apptacular in CFBuilder B2 apptacular v 1.000310. I am using multiserver instance of CF9.01 with MS 2008.
"About Apptacular
Version 1.000310 
Last Update Check 04/12/2011 07:11 AM 
Server Name localhost 
ColdFusion Version ColdFusion Server Developer 9,0,1,274733 
OS Version Windows 7 6.1 
ColdFusion Builder Version 2.0 "

Error
An Error has occured.
Message:Element IDENTITY.IDENTITY is undefined in a CFML structure referenced as part of an expression.

Details:

Any ideas? Thank you

**Comment by JohnnyP10** [comment]
Here is the code that i used to fix my problem: http://pastebin.com/sfkA8ASQ

Just replace the generateExcludedTables() method with the one in the link above.  The function should be found in handlers/cfc/db/datasource.cfc

This is not an official fix but it solved my problem.  Hopefully Terry will be able to release an official update to solve the bug, but the meanwhile try the method above.

**Comment by garence** [comment]
JohnnyP10 ... you are a rock star. Much thanks.

**Comment by htezcan** [comment]
Thank you, and I will try it tonight.
Haluk

**Comment by khooker** [comment]
Thanks for this patch.   I found I had to add these two tables to the same exclusion list:

```
           ,'sysaltfiles','database_mirroring_witnesses'
```

**Comment by OrhanCan** [comment]
http://pastebin.com/sfkA8ASQ        this URL banned  in my country, can i see the solution for MSSQL 2008 ?

**Comment by tpryan** [comment]
/**
     \* @hint Create a list of tables to not process.  Somehow pulled in via cfdbinfo in MSSQL
     */  
    private string function generateExcludedTables(){
        var excludedTableList = "'CHECK_CONSTRAINTS','COLUMN_DOMAIN_USAGE','COLUMN_PRIVILEGES',";
        excludedTableList = excludedTableList & "'COLUMNS','CONSTRAINT_COLUMN_USAGE','CONSTRAINT_TABLE_USAGE','DOMAIN_CONSTRAINTS','DOMAINS','KEY_COLUMN_USAGE',";
        excludedTableList = excludedTableList & "'PARAMETERS','REFERENTIAL_CONSTRAINTS','ROUTINE_COLUMNS','ROUTINES','SCHEMATA','TABLE_CONSTRAINTS',";
        excludedTableList = excludedTableList & "'TABLE_PRIVILEGES','TABLES','VIEW_COLUMN_USAGE','VIEW_TABLE_USAGE','VIEWS','all_columns','all_objects',";
        excludedTableList = excludedTableList & "'all_parameters','all_sql_modules','all_views','allocation_units','assemblies','assembly_files',";
        excludedTableList = excludedTableList & "'assembly_modules','assembly_references','assembly_types','asymmetric_keys','backup_devices','certificates',";
        excludedTableList = excludedTableList & "'check_constraints','column_type_usages','column_xml_schema_collection_usages','columns','computed_columns',";
        excludedTableList = excludedTableList & "'configurations','conversation_endpoints','conversation_groups','credentials','crypt_properties','data_spaces',";
        excludedTableList = excludedTableList & "'database_files','database_mirroring','database_mirroring_endpoints','database_permissions',";
        excludedTableList = excludedTableList & "'database_principal_aliases','database_principals','database_recovery_status','database_role_members',";
        excludedTableList = excludedTableList & "'databases','default_constraints','destination_data_spaces','dm_broker_activated_tasks','dm_broker_connections',";
        excludedTableList = excludedTableList & "'dm_broker_forwarded_messages','dm_broker_queue_monitors','dm_clr_appdomains','dm_clr_loaded_assemblies',";
        excludedTableList = excludedTableList & "'dm_clr_properties','dm_clr_tasks','dm_db_file_space_usage','dm_db_index_usage_stats',";
        excludedTableList = excludedTableList & "'dm_db_mirroring_connections','dm_db_missing_index_details','dm_db_missing_index_group_stats',";
        excludedTableList = excludedTableList & "'dm_db_missing_index_groups','dm_db_partition_stats','dm_db_session_space_usage','dm_db_task_space_usage',";
        excludedTableList = excludedTableList & "'dm_exec_background_job_queue','dm_exec_background_job_queue_stats','dm_exec_cached_plans',";
        excludedTableList = excludedTableList & "'dm_exec_connections','dm_exec_query_memory_grants','dm_exec_query_optimizer_info',";
        excludedTableList = excludedTableList & "'dm_exec_query_resource_semaphores','dm_exec_query_stats','dm_exec_query_transformation_stats',";
        excludedTableList = excludedTableList & "'dm_exec_requests','dm_exec_sessions','dm_fts_active_catalogs','dm_fts_index_population',";
        excludedTableList = excludedTableList & "'dm_fts_memory_buffers','dm_fts_memory_pools','dm_fts_population_ranges','dm_io_backup_tapes',";
        excludedTableList = excludedTableList & "'dm_io_cluster_shared_drives','dm_io_pending_io_requests','dm_os_buffer_descriptors','dm_os_child_instances',";
        excludedTableList = excludedTableList & "'dm_os_cluster_nodes','dm_os_hosts','dm_os_latch_stats','dm_os_loaded_modules','dm_os_memory_allocations',";
        excludedTableList = excludedTableList & "'dm_os_memory_cache_clock_hands','dm_os_memory_cache_counters','dm_os_memory_cache_entries',";
        excludedTableList = excludedTableList & "'dm_os_memory_cache_hash_tables','dm_os_memory_clerks','dm_os_memory_objects','dm_os_memory_pools',";
        excludedTableList = excludedTableList & "'dm_os_performance_counters','dm_os_ring_buffers','dm_os_schedulers','dm_os_stacks','dm_os_sublatches',";
        excludedTableList = excludedTableList & "'dm_os_sys_info','dm_os_tasks','dm_os_threads','dm_os_virtual_address_dump','dm_os_wait_stats',";
        excludedTableList = excludedTableList & "'dm_os_waiting_tasks','dm_os_worker_local_storage','dm_os_workers','dm_qn_subscriptions',";
        excludedTableList = excludedTableList & "'dm_repl_articles','dm_repl_schemas','dm_repl_tranhash','dm_repl_traninfo',";
        excludedTableList = excludedTableList & "'dm_tran_active_snapshot_database_transactions','dm_tran_active_transactions',";
        excludedTableList = excludedTableList & "'dm_tran_current_snapshot','dm_tran_current_transaction','dm_tran_database_transactions',";
        excludedTableList = excludedTableList & "'dm_tran_locks','dm_tran_session_transactions','dm_tran_top_version_generators',";
        excludedTableList = excludedTableList & "'dm_tran_transactions_snapshot','dm_tran_version_store','endpoint_webmethods','endpoints',";
        excludedTableList = excludedTableList & "'event_notification_event_types','event_notifications','events','extended_procedures',";
        excludedTableList = excludedTableList & "'extended_properties','filegroups','foreign_key_columns','foreign_keys','fulltext_catalogs',";
        excludedTableList = excludedTableList & "'fulltext_document_types','fulltext_index_catalog_usages','fulltext_index_columns','fulltext_indexes',";
        excludedTableList = excludedTableList & "'fulltext_languages','http_endpoints','identity_columns','index_columns','indexes','internal_tables',";
        excludedTableList = excludedTableList & "'key_constraints','key_encryptions','linked_logins','login_token','master_files','master_key_passwords',";
        excludedTableList = excludedTableList & "'message_type_xml_schema_collection_usages','messages','module_assembly_usages',";
        excludedTableList = excludedTableList & "'numbered_procedure_parameters','numbered_procedures','objects','openkeys','parameter_type_usages',";
        excludedTableList = excludedTableList & "'parameter_xml_schema_collection_usages','parameters','partition_functions','partition_parameters',";
        excludedTableList = excludedTableList & "'partition_range_values','partition_schemes','partitions','plan_guides','procedures','remote_logins',";
        excludedTableList = excludedTableList & "'remote_service_bindings','routes','schemas','securable_classes','server_assembly_modules',";
        excludedTableList = excludedTableList & "'server_event_notifications','server_events','server_permissions','server_principals','server_role_members',";
        excludedTableList = excludedTableList & "'server_sql_modules','server_trigger_events','server_triggers','servers','service_broker_endpoints',";
        excludedTableList = excludedTableList & "'service_contract_message_usages','service_contract_usages','service_contracts','service_message_types',";
        excludedTableList = excludedTableList & "'service_queue_usages','service_queues','services','soap_endpoints','sql_dependencies','sql_logins',";
        excludedTableList = excludedTableList & "'sql_modules','stats','stats_columns','symmetric_keys','synonyms','syscacheobjects','syscharsets',";
        excludedTableList = excludedTableList & "'syscolumns','syscomments','sysconfigures','sysconstraints','syscurconfigs','sysdatabases','sysdepends',";
        excludedTableList = excludedTableList & "'sysdevices','sysfilegroups','sysfiles','sysforeignkeys','sysfulltextcatalogs','sysindexes','sysindexkeys',";
        excludedTableList = excludedTableList & "'syslanguages','syslockinfo','syslogins','sysmembers','sysmessages','sysobjects','sysoledbusers',";
        excludedTableList = excludedTableList & "'sysopentapes','sysperfinfo','syspermissions','sysprocesses','sysprotects','sysreferences',";
        excludedTableList = excludedTableList & "'sysremotelogins','syssegments','sysservers','system_columns','system_components_surface_area_configuration',";
        excludedTableList = excludedTableList & "'system_internals_allocation_units','system_internals_partition_columns','system_internals_partitions',";
        excludedTableList = excludedTableList & "'system_objects','system_parameters','system_sql_modules','system_views','systypes','sysusers','tables',";
        excludedTableList = excludedTableList & "'tcp_endpoints','trace_categories','trace_columns','trace_event_bindings','trace_events',";
        excludedTableList = excludedTableList & "'trace_subclass_values','traces','transmission_queue','trigger_events','triggers',";
        excludedTableList = excludedTableList & "'type_assembly_usages','types','user_token','via_endpoints','views','xml_indexes',";
        excludedTableList = excludedTableList & "'xml_schema_attributes','xml_schema_collections','xml_schema_component_placements',";
        excludedTableList = excludedTableList & "'xml_schema_components','xml_schema_elements','xml_schema_facets','xml_schema_model_groups',";
        excludedTableList = excludedTableList & "'xml_schema_namespaces','xml_schema_types','xml_schema_wildcard_namespaces','xml_schema_wildcards'";
        excludedTableList = excludedTableList & ",'change_tracking_tables','change_tracking_databases','conversation_priorities','cryptographic_providers'";
        excludedTableList = excludedTableList & ",'database_audit_specification_details','database_audit_specifications','dm_audit_actions','dm_audit_class_type_map'";
        excludedTableList = excludedTableList & ",'dm_cdc_errors','dm_cdc_log_scan_sessions','dm_cryptographic_provider_properties','dm_database_encryption_keys'";
        excludedTableList = excludedTableList & ",'dm_db_mirroring_auto_page_repair','dm_db_mirroring_past_actions','dm_db_persisted_sku_features','dm_db_script_level'";
        excludedTableList = excludedTableList & ",'dm_exec_procedure_stats','dm_exec_trigger_stats','dm_filestream_file_io_handles','dm_filestream_file_io_requests','dm_fts_fdhosts'";
        excludedTableList = excludedTableList & ",'dm_fts_outstanding_batches','dm_os_dispatcher_pools','dm_os_dispatchers','dm_os_memory_brokers','dm_os_memory_node_access_stats'";
        excludedTableList = excludedTableList & ",'dm_os_memory_nodes','dm_os_nodes','dm_os_process_memory','dm_os_spinlock_stats','dm_os_sys_memory','dm_resource_governor_configuration'";
        excludedTableList = excludedTableList & ",'dm_resource_governor_resource_pools','dm_resource_governor_workload_groups','dm_server_audit_status','dm_tran_commit_table'";
        excludedTableList = excludedTableList & ",'dm_xe_map_values','dm_xe_object_columns','dm_xe_objects','dm_xe_packages','dm_xe_session_event_actions','dm_xe_session_events'";
        excludedTableList = excludedTableList & ",'dm_xe_session_object_columns','dm_xe_session_targets','dm_xe_sessions','fulltext_index_fragments','fulltext_stoplists'"; 
        excludedTableList = excludedTableList & ",'fulltext_stopwords','fulltext_system_stopwords','function_order_columns','resource_governor_configuration'"; 
        excludedTableList = excludedTableList & ",'resource_governor_resource_pools','resource_governor_workload_groups','server_audit_specification_details','server_audit_specifications'"; 
        excludedTableList = excludedTableList & ",'server_audits','server_event_session_actions','server_event_session_events','server_event_session_fields','server_event_session_targets'"; 
        excludedTableList = excludedTableList & ",'server_event_sessions','server_file_audits','server_principal_credentials','spatial_index_tessellations','spatial_indexes'"; 
        excludedTableList = excludedTableList & ",'spatial_reference_systems','sql_expression_dependencies','syscursorcolumns','syscursorrefs','syscursors','syscursortables'"; 
        excludedTableList = excludedTableList & ",'table_types','trigger_event_types'"; 
        return excludedTableList;
    }

**Comment by OrhanCan** [comment]
is that only changes? do i have to replace  something?

**Comment by OrhanCan** [comment]
i purchased CFB2.0.1  only for Apptacular , this doesnt work for me...

**Comment by OrhanCan** [comment]
this is not solution...

**Comment by martypaz** [comment]
FIX FOR SQL SERVER ONLY!!!

I wrote this simple script to get the names of all the system views in SQL server - I'm sure M$ add new tables and as Terry appears to no longer develop apptacular he won;t be aware of the new views. Simply run the script and copy and paste the list of views it creates. Instructions will be displayed after running the script........

&lt;cfdbinfo name="dbi" datasource="yourdatasource" type="Tables"&gt;
&lt;cfquery name="dbi" dbtype="query" &gt;
    select \* from dbi where table_type='VIEW'
&lt;/cfquery&gt;
&lt;cfoutput&gt;
    Copy the quoted values below and paste them at the bottom of /handlers/cfc/db/datasource.cfc just below the last excludedTableList (About line 455)&lt;br&gt;&lt;br&gt;
    excludedTableList = excludedTableList & ",#replace(listQualify(valuelist(dbi.table_name), "'"), ",'", ", '", "all")#";
&lt;/cfoutput&gt;

Hope it helps

**Comment by tpryan** [comment]
Yeah, I'm not actively maintaining. But if you can put together a pull request I'll approve it.
