### ISSUE TITLE
errors when running ColdFusion on a specific port

### ISSUE THREAD

**Issue by guustnieuwenhuis** [tpryan/Apptacular#28]
I've got ColdFusion 9 running on port 8502 and because of that Apptacular throws the following error: "The requested URL was not found on this server."

These are the files in witch the problem occurs:
Apptacular/handlers/handlerAbout.cfm - line 2 - 
Apptacular/handlers/handlerActiveTables.cfm - line 9 - 
Apptacular/handlers/ handlerEditConfig.cfm - line 7 - 
Apptacular/handlers/handlerEditDB.cfm - line 9
Apptacular/handlers/handlerPurge.cfm - line 9

This is a correction that fixed the problem:
<cfset handlerURL = "http://" & cgi.server_name & ":" & cgi.server_port & handlerPath />

**Comment by tpryan** [comment]
Closed by 0bd8f0ef30a14fbef530dec304957d80b9f79358 Certain handlers were not working on ColdFusion servers with ports other then 80.

**Comment by ArmorBearerSlave** [comment]
This works!  I only had to change two files handlerEditDB.cfm and handlerEditConfig.cfm.  Thanks!
