### ISSUE TITLE
Error when opening "About Apptacular"

### ISSUE THREAD

**Issue by guustnieuwenhuis** [tpryan/Apptacular#29]
When I open the "About Apptacular"-page I get the following error:
"The requested URL /Apptacular/handlers/about/index.cfm&ideVersion=1.0 was not found on this server."

The "&" should be replaced by a "?".

**Comment by tpryan** [comment]
Closed by 97797afb7cc0f17344bbd749aa08a71c99687deb
A recently added flag to support Storm caused issues with handlers without Query strings.
