### ISSUE TITLE
Apptacular error in Windows 7 ColdFusion Builder 2 Beta on Create Application

### ISSUE THREAD

**Issue by stevebb1** [tpryan/Apptacular#32]
An Error has occured.
Message:Invalid CFML construct found on line 212 at column 25.

Details:ColdFusion was looking at the following text:

for

The CFML compiler was processing:

A script statement beginning with for on line 212, column 25.
A script statement beginning with { on line 209, column 65.
A script statement beginning with for on line 209, column 17.
A script statement beginning with public on line 199, column 9.

**Comment by tpryan** [comment]
What version of ColdFusion are you running it on?

**Comment by stevebb1** [comment]
CF 9 (latest)

**Comment by tpryan** [comment]
Can you provide the logs files from /apptacular/logs?

**Comment by stevebb1** [comment]
It's a mess but here you go:

struct Column: 25 Detail: ColdFusion was looking at the following text:

for

The CFML compiler was processing:

```
* A script statement beginning with for on line 212, column 25.
* A script statement beginning with { on line 209, column 65.
* A script statement beginning with for on line 209, column 17.
* A script statement beginning with public on line 199, column 9.
```

KnownColumn: 39 KnownLine: 211 KnownText: ; Line: 212 Message: Invalid CFML construct found on line 212 at column 25. Snippet: for(var key in StackTrace: coldfusion.compiler.ParseException: Invalid CFML construct found on line 212 at column 25. at coldfusion.compiler.cfml40.generateParseException(cfml40.java:11961) at coldfusion.compiler.cfml40.jj_consume_token(cfml40.java:11832) at coldfusion.compiler.cfml40.ComplexStatement(cfml40.java:1708) at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1478) at coldfusion.compiler.cfml40.cfscriptBlock(cfml40.java:2321) at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1518) at coldfusion.compiler.cfml40.ComplexStatement(cfml40.java:1623) at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1478) at coldfusion.compiler.cfml40.functionDefinition(cfml40.java:2955) at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1523) at coldfusion.compiler.cfml40.start(cfml40.java:4508) at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:703) at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:648) at coldfusion.compiler.NeoTranslator.parseAndTransform(NeoTranslator.java:401) at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:343) at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:144) at coldfusion.runtime.TemplateClassLoader$TemplateCache$1.fetch(TemplateClassLoader.java:418) at coldfusion.util.LruCache.get(LruCache.java:180) at coldfusion.runtime.TemplateClassLoader$TemplateCache.fetchSerial(TemplateClassLoader.java:362) at coldfusion.util.AbstractCache.fetch(AbstractCache.java:58) at coldfusion.util.SoftCache.get_statsOff(SoftCache.java:133) at coldfusion.util.SoftCache.get(SoftCache.java:81) at coldfusion.runtime.TemplateClassLoader.findClass(TemplateClassLoader.java:591) at coldfusion.runtime.RuntimeServiceImpl.getFile(RuntimeServiceImpl.java:785) at coldfusion.runtime.RuntimeServiceImpl.resolveTemplatePath(RuntimeServiceImpl.java:766) at coldfusion.runtime.TemplateProxyFactory.getTemplateFileHelper(TemplateProxyFactory.java:1505) at coldfusion.cfc.ComponentProxyFactory.getProxy(ComponentProxyFactory.java:51) at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:8351) at coldfusion.runtime.CFPage._createObject(CFPage.java:8338) at cfhandlerCreateProject2ecfm1897094416.runPage(C:\inetpub\wwwroot\Apptacular\handlers\handlerCreateProject.cfm:6) at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:231) at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:416) at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:342) at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at coldfusion.filter.PathFilter.invoke(PathFilter.java:87) at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:27) at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70) at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:74) at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:53) at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126) at coldfusion.CfmServlet.service(CfmServlet.java:200) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at jrun.servlet.FilterChain.doFilter(FilterChain.java:86) at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at jrun.servlet.FilterChain.doFilter(FilterChain.java:94) at jrun.servlet.FilterChain.service(FilterChain.java:101) at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106) at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42) at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286) at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543) at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203) at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320) at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428) at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266) at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66) TagContext: [array] 1) [struct] COLUMN: 25 LINE: 212 TEMPLATE: C:\inetpub\wwwroot\Apptacular\handlers\cfc\utils\builderHelper.cfc TYPE: SYNTAX 2) [struct] COLUMN: 0 ID: CF_CFPAGE LINE: 6 RAW_TRACE: at cfhandlerCreateProject2ecfm1897094416.runPage(C:\inetpub\wwwroot\Apptacular\handlers\handlerCreateProject.cfm:6) TEMPLATE: C:\inetpub\wwwroot\Apptacular\handlers\handlerCreateProject.cfm TYPE: CFML TokenText: for Type: Template snippet: for(var key in ***********************************************************************************\*

**Comment by k-sea** [comment]
yeah, same error here as well.

**Comment by tpryan** [comment]
This should be fixed.  Run an Apptacular update.

**Comment by stevebb1** [comment]
Thanks Terrence. That did the trick.
