### ISSUE TITLE
error when opening "edit database data model"

### ISSUE THREAD

**Issue by guustnieuwenhuis** [tpryan/Apptacular#33]
"The specified directory /dev/null does not exist."

The error occurred in /Applications/ColdFusion9/wwwroot/Apptacular/handlers/editDB/editDatasource.cfm: line 15
13 :    variables.NL = createObject("java", "java.lang.System").getProperty("line.separator");
14 :    variables.FS = createObject("java", "java.lang.System").getProperty("file.separator");  
15 :    files = DirectoryList(schemaPath, true, "query", "*.xml");
16 : </cfscript>
17 :

**Comment by tpryan** [comment]
Underlying error here is that the .apptacular config has gotten corrupted or is missing. Fixing with better error messages, doesn't solve the underlying corruption problem though.

**Comment by tpryan** [comment]
Made some changes to error trapping for editDatasource.  Should now
catch a corrupted or missign .apptacular configuration. 

Closed by 15caecab97d922e6062b52941a4c8591d9df1237
