### ISSUE TITLE
An Error has occured (Invalid CFML construct)

### ISSUE THREAD

**Issue by Tovanu** [tpryan/Apptacular#35]
Hey,
Just installed a fresh copy of the cfbuilder 2 beta and I was anxious to try out the apptacular extension, I am however face with an error.
Here is the entire log:
http://pastebin.com/raw.php?i=HGNyRvy7

Hope this can be resolved =)

**Comment by tpryan** [comment]
Should be fixed now.  Run an update.

**Comment by tpryan** [comment]
Made fixes to BuilderHelper to support versions of ColdFusion previous
to 9.01. 

Builder helper had array loops that used the &quot;for in&quot; array loop
syntax. 

Closed by 6c8b5318e231fce856ac0658e3afa340cdaf5077
Closed by 6c8b5318e231fce856ac0658e3afa340cdaf5077
