### ISSUE TITLE
Error on Create Application with new CF Builder Beta 2 install and Apptacular 1.000310

### ISSUE THREAD

**Issue by marty-mcgee** [tpryan/Apptacular#36]
On any attempt to "Create Application", Apptacular throws this error:

Error
An Error has occured.
Message:Cannot access array element at position 2.
Details:The array has 1 indexes. Valid positions are from 1 to 1.

Here is the complete log:

struct Detail: The array has 1 indexes. Valid positions are from 1 to 1. ErrNumber: 0 Message: Cannot access array element at position 2. StackTrace: coldfusion.runtime.InvalidArrayIndexException: Cannot access array element at position 2. at coldfusion.runtime.Array.ArrayIsDefined(Array.java:266) at coldfusion.runtime.CFPage.ArrayIsDefined(CFPage.java:529) at cftable2ecfc1470774065$funcCALCULATEFOREIGNKEYLABEL.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\table.cfc:152) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582) at cftable2ecfc1470774065$funcINIT.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\table.cfc:110) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:490) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:336) at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:8370) at coldfusion.runtime.CFPage._createObject(CFPage.java:8338) at cfdatasource2ecfc1002938553$funcPOPULATETABLES.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\datasource.cfc:93) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:2582) at cfdatasource2ecfc1002938553$funcINIT.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\datasource.cfc:35) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:490) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:336) at coldfusion.runtime.CFPage.___createObjectInternal(CFPage.java:8370) at coldfusion.runtime.CFPage._createObject(CFPage.java:8338) at cfhandlerGenerate2ecfm1091199144.runPage(C:\CF9\wwwroot\Apptacular\handlers\handlerGenerate.cfm:183) at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:231) at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:416) at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:342) at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at coldfusion.filter.PathFilter.invoke(PathFilter.java:87) at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:27) at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70) at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:53) at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126) at coldfusion.CfmServlet.service(CfmServlet.java:200) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at jrun.servlet.FilterChain.doFilter(FilterChain.java:86) at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at jrun.servlet.FilterChain.doFilter(FilterChain.java:94) at jrun.servlet.FilterChain.service(FilterChain.java:101) at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106) at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42) at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286) at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543) at jrun.servlet.jrpp.JRunProxyService.invokeRunnable(JRunProxyService.java:203) at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320) at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428) at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266) at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66) TagContext: [array] 1) [struct] COLUMN: 0 ID: CF_CFPAGE LINE: 152 RAW_TRACE: at cftable2ecfc1470774065$funcCALCULATEFOREIGNKEYLABEL.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\table.cfc:152) TEMPLATE: C:\CF9\wwwroot\Apptacular\handlers\cfc\db\table.cfc TYPE: CFML 2) [struct] COLUMN: 0 ID: CF_UDFMETHOD LINE: 110 RAW_TRACE: at cftable2ecfc1470774065$funcINIT.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\table.cfc:110) TEMPLATE: C:\CF9\wwwroot\Apptacular\handlers\cfc\db\table.cfc TYPE: CFML 3) [struct] COLUMN: 0 ID: CF_CFPAGE LINE: 93 RAW_TRACE: at cfdatasource2ecfc1002938553$funcPOPULATETABLES.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\datasource.cfc:93) TEMPLATE: C:\CF9\wwwroot\Apptacular\handlers\cfc\db\datasource.cfc TYPE: CFML 4) [struct] COLUMN: 0 ID: CF_UDFMETHOD LINE: 35 RAW_TRACE: at cfdatasource2ecfc1002938553$funcINIT.runFunction(C:\CF9\wwwroot\Apptacular\handlers\cfc\db\datasource.cfc:35) TEMPLATE: C:\CF9\wwwroot\Apptacular\handlers\cfc\db\datasource.cfc TYPE: CFML 5) [struct] COLUMN: 0 ID: CF_CFPAGE LINE: 183 RAW_TRACE: at cfhandlerGenerate2ecfm1091199144.runPage(C:\CF9\wwwroot\Apptacular\handlers\handlerGenerate.cfm:183) TEMPLATE: C:\CF9\wwwroot\Apptacular\handlers\handlerGenerate.cfm TYPE: CFML Type: Expression len: 1 pos: 2 ***********************************************************************************\*

**Comment by ghost** [comment]
Hey there;
Any chance you worked out a solution to this?
I am getting the same issue.

Beau.

**Comment by marty-mcgee** [comment]
Hey Gavin. No, I haven't had much luck with getting Apptacular to work as
advertised. Please keep me posted if you find the answer. Thanks -- Marty
McGee
On Jul 18, 2011 1:44 AM, "gavinbaumanis" <
reply@reply.github.com>
wrote:

**Comment by odhranhardy** [comment]
Guys,

I've come across the same problem and thought I'd fire my findings up here.
The problem is with a bug in CF8 and CF9, I believe it has been fixed in CF9.1, but I haven't tested that yet.

The problem lies with the ArrayIsDefined() function which has a bug, resulting in an error when you pass it an index greater than the size of the array.
The quick fix is the change the conditional logic to to check for the length of the array as well.

I Updated the Apptacular\handlers\cfc\db\table.cfc and changed line 152 from 

if (ArrayIsDefined(columns, i+1)){

to

if (arrayLen(columns) gte i+1 and ArrayIsDefined(columns, i+1)){

and this fixes the error during code generation.

Hopefully this helps someone else.

Regards,
Odhran Hardy.

**Comment by marty-mcgee** [comment]
I'd like to add you to my professional network on LinkedIn.
- Marty

Marty McGee
Lead Web Application Developer at Cruiser Customizing, Inc.
San Francisco Bay Area

Confirm that you know Marty McGee:
https://www.linkedin.com/e/-rwwjpy-gsezgfhz-6a/isd/4158433937/AYDFy_k-/?hs=false&tok=1nii0Xg_lHC4U1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/-rwwjpy-gsezgfhz-6a/qp-QMY9aXRP0imTj1LNHBR05AN0Aqonnkkgmbgf7IN5UVOnLjogzygf57MSUH7nMCkcqql97AP5SjaVKtHsmDxsWRs13JdntuY02Br/goo/reply%2Bi-708443-9157cf8ae5f9677603f128da13943350e3edcb97%40reply%2Egithub%2Ecom/20061/I1435239151_1/?hs=false&tok=0VEHBwgnpHC4U1

(c) 2011 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.

**Comment by marty-mcgee** [comment]
Inactive application.
