### ISSUE TITLE
Error on cfc.utils.utils file

### ISSUE THREAD

**Issue by msinaysky** [tpryan/Apptacular#39]
Receiving error when trying to use Apptacular (Log file was not created):

"Invalid CFML construct found on line 15 at column 21.  
ColdFusion was looking at the following text:
cfc.utils.utils

The CFML compiler was processing:

A script statement beginning with utils on line 15, column 9.
A cfscript tag beginning on line 12, column 2."

I am running CF8 on WindowsXP.. Error message popup as soon as I am creating new project in CFBuilder and getting to the screen "Add existing Sources and Extensions" and adding "Apptacular". If I ignoring this error and later on try to use "Apptacular" to any DB tables I am receiving the same Error.

Thanks

Michael Sinaysky

**Comment by tpryan** [comment]
What version of ColdFusion are you running?

**Comment by msinaysky** [comment]
ColdFusiion 8.0.1

**Comment by tpryan** [comment]
Apptacular only supports cf 9.+.

I should add a better trap for that.

**Comment by msinaysky** [comment]
Thanks
